-- ============================================================
-- テストデータ投入（新仕様：家族構成フィールドなし）
-- Supabase SQL Editor に貼り付けて実行してください
-- ============================================================

-- 既存テストデータをリセット（任意）
-- DELETE FROM companies WHERE company_name LIKE 'テスト%';

INSERT INTO companies (
  is_hidden,
  registered_at,
  star_rating,
  company_name,
  company_name_kana,
  company_phone,
  company_fax,
  birth_era,
  birth_year,
  birth_month,
  birth_day,
  gender,
  rep_name,
  rep_name_kana,
  mobile_phone,
  home_phone,
  email,
  company_address_type,
  company_address_owner,
  company_postal_code,
  company_prefecture,
  company_city,
  company_street,
  rep_address_same,
  rep_address_type,
  rep_address_owner,
  rep_postal_code,
  rep_prefecture,
  rep_city,
  rep_street,
  capital,
  monthly_revenue,
  employees,
  founded_year,
  purchase_amount,
  purchase_date,
  payday,
  total_salary,
  business_description,
  current_account,
  payment_schedule,
  tax_payment_status,
  tax_payment_detail,
  other_companies,
  notes
) VALUES
(
  false,
  '2026-05-08',
  5,
  '株式会社カンシアリンク',
  'カブシキガイシャカンシアリンク',
  '06-1234-5678',
  '06-1234-5679',
  'S',
  45,
  3,
  15,
  '男性',
  '山田 太郎',
  'ヤマダ タロウ',
  '090-1234-5678',
  '06-9876-5432',
  'yamada@kansia-link.co.jp',
  '賃貸',
  '山田太郎',
  '530-0001',
  '大阪府',
  '大阪市北区',
  '梅田1-1-1 梅田ビル5F',
  false,
  '所有',
  '山田太郎',
  '530-0011',
  '大阪府',
  '大阪市北区',
  '大深町4-20-101',
  500,
  1200,
  15,
  2005,
  800,
  '2026-06-30',
  25,
  85,
  '不動産売買・賃貸管理・建設工事・リフォーム工事の企画・設計・施工・監理',
  'あり',
  '[
    {"company":"株式会社ABCファイナンス","address":"東京都渋谷区渋谷1-1-1","amount":"300万円","condition1":"毎月末日","condition2":"翌月払い"},
    {"company":"DEF信用金庫","address":"大阪府大阪市中央区心斎橋2-2-2","amount":"150万円","condition1":"15日締め","condition2":"月末払い"},
    {"company":"GHIリース株式会社","address":"兵庫県神戸市中央区三宮3-3-3","amount":"50万円","condition1":"都度","condition2":""}
  ]',
  '完納',
  '',
  'XYZ銀行 梅田支店にて事業資金ローン利用中（残高200万円）',
  '優良顧客。長期取引実績あり。担当者：田中'
),
(
  false,
  '2026-05-10',
  4,
  '有限会社大阪商事',
  'ユウゲンガイシャオオサカショウジ',
  '06-2345-6789',
  '06-2345-6780',
  'H',
  5,
  7,
  22,
  '男性',
  '鈴木 一郎',
  'スズキ イチロウ',
  '080-2345-6789',
  '06-8765-4321',
  'suzuki@osaka-shoji.co.jp',
  '所有',
  '鈴木一郎',
  '542-0081',
  '大阪府',
  '大阪市中央区',
  '南船場2-3-4 南船場ビル3F',
  true,
  '所有',
  '鈴木一郎',
  '542-0081',
  '大阪府',
  '大阪市中央区',
  '南船場2-3-4 南船場ビル3F',
  100,
  450,
  8,
  1993,
  300,
  '2026-07-15',
  20,
  45,
  '衣料品・雑貨の卸売・小売業。EC事業も展開中。',
  'なし',
  '[
    {"company":"MNOクレジット","address":"大阪府堺市堺区1-1","amount":"100万円","condition1":"月末締め","condition2":"翌々月払い"},
    {"company":"","address":"","amount":"","condition1":"","condition2":""},
    {"company":"","address":"","amount":"","condition1":"","condition2":""}
  ]',
  '完納',
  '',
  '',
  '2回目の相談。前回は条件が合わず見送り。'
),
(
  false,
  '2026-05-12',
  3,
  '合同会社テスト商店',
  'ゴウドウガイシャテストショウテン',
  '03-3456-7890',
  '',
  'H',
  3,
  11,
  30,
  '女性',
  '田中 花子',
  'タナカ ハナコ',
  '070-3456-7890',
  '',
  'tanaka@test-shoten.jp',
  '賃貸',
  '田中花子',
  '160-0023',
  '東京都',
  '新宿区',
  '西新宿7-7-7 新宿センタービル10F',
  false,
  '賃貸',
  '田中花子',
  '160-0022',
  '東京都',
  '新宿区',
  '新宿5-5-5-202',
  50,
  200,
  3,
  2021,
  150,
  null,
  15,
  28,
  'インターネット通販・フリーランス向けサービス業',
  'なし',
  '[
    {"company":"","address":"","amount":"","condition1":"","condition2":""},
    {"company":"","address":"","amount":"","condition1":"","condition2":""},
    {"company":"","address":"","amount":"","condition1":"","condition2":""}
  ]',
  '未納',
  '消費税 45万円（令和5年分）。分割納付交渉中。',
  'PQR銀行カードローン残高80万円',
  '初回相談。資金繰り改善が主な目的。'
);
